server:
    port: 8081
katool:
    lock:
        internalLockLeaseTime: 30   # 分布式锁默认租约时间
        timeUnit: seconds           # 租约时间单位
    util:
        redis:
            policy: "caffeine"      # 选择内存缓存策略，caffeine
            exptime: {5*60*1000}           # LFU过期时间
            time-unit: milliseconds #  过期时间单位

spring:
    redis:
        database: 1
        host: 127.0.0.1
        port: 6379
        timeout: 5000
        lettuce:
            pool:
                max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
                max-idle: 100 # 连接池中的最大空闲连接
                min-idle: 3 # 连接池中的最小空闲连接
                max-wait: 5000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）